x-spark-common: &spark-common
  image: bitnami/spark:latest
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
  networks:
    - airflow-net

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - airflow.env
  volumes:
    - ./jobs:/opt/airflow/jobs
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./test:/opt/airflow/test
    - ./server:/opt/airflow/server
    - ./bucket:/opt/airflow/bucket
  depends_on:
    - postgres
  networks:
    - airflow-net

services:

  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - airflow-net

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080" # airflow web server
      - "8000:8000"
    depends_on:
      - scheduler

  scheduler:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username airflow --firstname angel --lastname lm --role Admin --email m.eng.angel.manriquez@gmail.com --password airflow && airflow scheduler"

networks:
  airflow-net:
